name: QAQC dam data
on:
   push:
      branches: [ ccre-dam-data ]
      #paths: 
      #- 'ccre-waterquality.csv'
   workflow_dispatch:


jobs:
  qaqc_run:
     runs-on: ubuntu-latest
     container:
      image: rocker/tidyverse:latest
     steps:
       - name: Checkout repo
         uses: actions/checkout@v3
         with:
           ref: ccre-dam-data
           fetch-depth: 1
       - name: Run QAQC script
         run:  | 
           R -e 'install.packages(c("EDIutils","xml2","here","suncalc"))'
           Rscript $GITHUB_WORKSPACE/R/QAQC_workflow.R
           Rscript $GITHUB_WORKSPACE/R/QAQC_met_workflow.R

       - name: Commit files
         run: |
            git config --global --add safe.directory $GITHUB_WORKSPACE
            git config --local user.name "$GITHUB_ACTOR"
            git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
            ggit checkout ccre-dam-data-qaqc
            git add ccre-waterquality_L1.csv
            git add ccre_met_L1.csv
            git commit -m "Updating QAQC files" || echo "No changes to commit"
            git push || echo "No changes to commit"
